apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "trackhub.fullname" . }}-config
  labels:
    {{- include "trackhub.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.config.appEnv | quote }}
  DEFAULT_PRIORITY: {{ .Values.config.defaultPriority | quote }}