# DVO-L3-7F2A91
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
  namespace: trackhub
  labels:
    app: devops-app
    mascot: kabachok
  annotations:
    devops-lab/mascot: "кабачок"
    devops-lab/mascot-approved: "true"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
        mascot: kabachok
      annotations:
        devops-lab/mascot: "кабачок"
        devops-lab/mascot-approved: "true"
    spec:
      containers:
      - name: devops-app
        image: ghcr.io/vlad8800/devops:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: trackhub-config
        - secretRef:
            name: trackhub-secret
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 5