# DVO-L3-7F2A91
apiVersion: v1
kind: Secret
metadata:
  name: trackhub-secret
  namespace: trackhub
  labels:
    app: devops-app
    mascot: kabachok
  annotations:
    devops-lab/mascot: "кабачок"
    devops-lab/mascot-approved: "true"
type: Opaque
stringData:
  DATABASE_URL: "sqlite:///./test.db"
  API_SECRET_KEY: "super-secret-key-123"