# DVO-L3-7F2A91
apiVersion: v1
kind: Secret
metadata:
  name: trackhub-secret
  namespace: trackhub
  labels:
    app: devops-app
type: Opaque
data:
  DATABASE_URL: c3FsaXRlOi8vLy4vdGVzdC5kYg==
  API_SECRET_KEY: c3VwZXItc2VjcmV0LWtleS0xMjM=
